### ISSUE TITLE
Use uniform approach for position testing in cypress

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#106]
As @HendrikThePendric notes here: https://github.com/dhis2/ui/pull/102#discussion_r429754967, we're now using different ways to test position. We should unify that so that we use a single approach.

**Comment by HendrikThePendric** [comment]
@ismay I have forgotten what our preferred solution would look like. 

Shall we go for the bare metal approach? Like this one👇 
https://github.com/dhis2/ui/blob/1704fbd17b75c0ddbb326a9361eaf85992e6a6c3/cypress/integration/SingleSelect/position/index.js#L32-L48

Or shall we go for the approach [you took here](https://github.com/dhis2/ui/pull/102#pullrequestreview-417485432)?
```javascript
cy.getPositionsBySelectors(
    '[data-test="dhis2-uicore-menuitem"]',
    '[data-test="submenu"]'
).should(([menuItemRect, subMenuRect]) => {
```

I have a slight preference for the second approach but I'm also fine with the first.

**Comment by Mohammer5** [comment]
I think it should be fine to have a mixed approach. We already have the `all` selector, combined, it could look something like this:


```js
cy.all(
  () => cy.get('[data-test="dhis2-uicore-menuitem"]').getPosition(),
  () => cy.get('[data-test="submenu"]').getPosition(),
).should(([menuItemRect, subMenuRect]) => { /* ... */ })
```

The `getPosition` command could stay but works on a `prevSubject` while using the `all` command to do it multiple times "at once".

**Comment by HendrikThePendric** [comment]
I really like @Mohammer5's suggestion. Probably I would go with something like `getRect` instead of `getPosition`. I came up with the name `getPositionsBySelectors`, and the fact that this returns `rects`, and each `rect` doesn't just contain position data (i.e. top, right, bottom, left) but also width and height has bothered me ever since.

**Comment by ismay** [comment]
I'd personally prefer going with the bare metal approach. I've not seen _that_ much position testing in UI, so for me the added indirection and maintenance don't seem worth the convenience of abstraction.

**Comment by HendrikThePendric** [comment]
> I've not seen that much position testing in UI

There are 34 scenarios that assert a position. I think that's quite a lot, right?

**Comment by ismay** [comment]
> > I've not seen that much position testing in UI
> 
> There are 34 scenarios that assert a position. I think that's quite a lot, right?

Yeah it's more than a few. I guess I just find the custom helpers not that necessary vs the manual approach. But my opinion is in the minority I think 😊

**Comment by HendrikThePendric** [comment]
It's just a shame you can't write code like this:
```
cy.all(
  () => cy.get('[data-test="dhis2-uicore-menuitem"]').get(0).getBoundingClientRect(),
  () => cy.get('[data-test="submenu"]').get(0).getBoundingClientRect(),
).should(([menuItemRect, subMenuRect]) => { /* ... */ })
```
IMO that'd be nicest...

**Comment by Mohammer5** [comment]
You could get close to the example:

```js
cy.get('[data-test="submenu"]').invoke(get, 0).then(el => el.getBoundingClientRect())
```

**Comment by HendrikThePendric** [comment]
How does that affect the retrying? When we mix `then` with `should`? Are we OK here?

**Comment by Mohammer5** [comment]
`cy.get('[data-test="submenu"]')` will retry until the element has been found. `.invoke('get', 0)` just gets the first in the set. If there's no element, the `cy.get` will cause the test to fail (which is the expected behavior). `.then` should therefore be safe to use here I suppose.

**Comment by HendrikThePendric** [comment]
So to summarise:
- We'd like to use helpers as little as possible
- We do position assertions quite a lot, so something succinct would be prefereable
- From a retry-ability perspective, we can use `then` if it is chained to a `get`

And @Mohammer5 already suggested a great one-liner combining `invoke` with `then`:
```javascript
cy.get('[data-test="submenu"]').invoke('get', 0).then(el => el.getBoundingClientRect())
```

But I think that considering the fact that we are already using `then` we can skip using the call to `invoke`:
```javascript
cy.get('[data-test="submenu"]').then($el => $el.get(0).getBoundingClientRect())
```

So if you agree with the above, I suggest that we settle on this syntax:
```javascript
cy.all(
  () => cy.get('[data-test="dhis2-uicore-menuitem"]').then($el => $el.get(0).getBoundingClientRect()),
  () => cy.get('[data-test="submenu"]')then($el => $el.get(0).getBoundingClientRect()),
).should(([menuItemRect, subMenuRect]) => { /* ... */ })
```

**Comment by ismay** [comment]
One thing I'd change:

> * From a retry-ability perspective, we can use then if it is chained to a get

We can only use `then` after a `get` if we're expecting a single element. Otherwise this pattern could yield unpredictable results.

**Comment by Mohammer5** [comment]
In this get, `.invoke('get', 0)` will yield exactly one DOM element (not jQuery element)

**Comment by HendrikThePendric** [comment]
After discussing a little bit more on Slack and realising what prettier does to the long one-liners I suggested above, I went with a small variation on the approach @ismay suggested:
https://github.com/dhis2/ui/blob/0356ec0a115851ec3b51b2266b392e86a9e69ac7/cypress/integration/Popper/accepts_different_reference_types/index.js#L20-L33
