### ISSUE TITLE
Implement `conditional` prop-type where appropriate

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui#11]
This new prop-type introduced in https://github.com/dhis2/prop-types/pull/113 is more powerful/restrictive than just using `propTypes.oneOfType`, so we should use it where possible.

Steps:
- Do a global search in our codebase for `propTypes.oneOfType`
- Evaluate on a case-by-case basis if switching to the new prop-type would be appropriate

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-78
