### ISSUE TITLE
Explore adding support for an interactive documentation / code gen

### ISSUE THREAD

**Issue by amcgee** [dhis2/ui#135]
This could be something as simple as a `codePen` example which people can edit, but it would also be quite powerful to generate a form based on a component's PropTypes, allow the user to fill out that form and (a) see a demo of the component based on the props they selected, (b) copy-and-paste the JSX for that component into their project.

We don't want to reinvent the wheel here, so we should look around for existing solutions if they exist.

**Comment by ismay** [comment]
I like the idea of a codepen example (or codesandbox.io, which final-form uses as well). Seems simple enough for us to add, and we'd only have to maintain the examples themselves.

**Comment by HendrikThePendric** [comment]
Some inspiration of how far we can possibly take our storybook demo/docs site can be found [here](https://storybook.js.org/docs/examples/). I especially liked the [wix-style-react](https://wix-style-react.now.sh/) site.

**Comment by HendrikThePendric** [comment]
The [Coursera UI](https://building.coursera.org/coursera-ui/) site includes some interactive examples, but unfortunately the source-code for that doesn't seem to be available.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-54
