### ISSUE TITLE
Our storybook demos aren't interactive

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#136]
Our components are controlled, so they need a wrapper for certain behaviour. We don't include this in our storybook demos because it causes the wrapper to show up in the jsx example, which seems confusing.

@HendrikThePendric mentioned that maybe there's a way to add a wrapper that won't show up in storybook. Though then I wonder if users would maybe expect the component to work without a wrapper.

At any rate, our components not responding to certain input in the demos could be confusing. It'd be good to discuss how we could make it less confusing/unexpected.

**Comment by ismay** [comment]
We could also clearly indicate that these examples aren't interactive, and link to the interactive examples mentioned in #135

**Comment by ismay** [comment]
Also, besides not being interactive, certain interactive behaviour might also be confusing. The select demos for example show alerts on selection in some cases, which might make sense to us as maintainers, but is not in line with what you'd expect a select to do.

**Comment by HendrikThePendric** [comment]
The stories are currently static to demo what different props do. I don’t think there is anything wrong with that per se. But I do think it would benefit a lot of components if we were to add a “functional example” as well.

So my suggestion would be to add fully functional examples where appropriate, i.e. not replace what we currently have but add to it. The demos we have now doen't have any distractions and that's a good thing most of the time. But we should also demo how you would actually use the component in a more real-world scenario. In these demos we should showcase how you'd "wire-up" the component to make it interactive/stateful, so we should make sure the code to achieve that is included in the JSX panel as well. 

Probably using a storybook decorator is not really suitable for what I described above.

**Comment by HendrikThePendric** [comment]
Some inspiration of how far we can possibly take our storybook demo/docs site can be found [on the storybook examples page](https://storybook.js.org/docs/examples/). I especially liked the [wix-style-react](https://wix-style-react.now.sh/) site.

**Comment by Mohammer5** [comment]
Here's how I did that for the testing stories of the Transfer component, we could easily adopt that in our demo stories and it wouldn't show up in the jsx:

* [statefulDecorator.js](https://github.com/dhis2/ui/blob/master/packages/widgets/src/Transfer/__e2e__/common/statefulDecorator.js)
* [add_remove-highlighted-options.stories.e2e.js](https://github.com/dhis2/ui/blob/master/packages/widgets/src/Transfer/__e2e__/add_remove-highlighted-options.stories.e2e.js)

We could then create stories that start with `Interactive` / `Controlled` (maybe `Controlled` is better because it indicated that the component is interactive AND controlled).

**Comment by ismay** [comment]
By the way, I noticed in the docs for the jsx plugin for storybook that you have manual control over what shows up in the jsx example and what doesn't. If we need fine-grained control over that we should check the docs: https://github.com/storybookjs/addon-jsx

Question is still how much we need to show/hide for the story not to confuse the user, but at least the option is there.

**Comment by ismay** [comment]
Also mentioned in this thread: https://dhis2.slack.com/archives/CBM8LNEQM/p1592466715117600

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-53
