### ISSUE TITLE
Cypress test failure on master (unreachable storybook)

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#137]
See here: https://github.com/dhis2/ui/runs/734497101

There seems to be a 60 second timeout set on localhost:5001 becoming available: https://github.com/dhis2/ui/runs/734497101#step:3:57

I assume that that's the cause for the task not always failing. Apparently it sometimes becomes available within the time limit.

**Comment by Mohammer5** [comment]
@ismay and I have talked about it and concluded that it'd make sense to increase the default timeout from 60s to 5m, which should be a reasonable max time. If it took any longer, it'd hint at there being a problem with the CI process.

The config for the `wait-on` module is `-t` / `--timeout`.
For some reason the documentation of the `wait-on` module states that the default value is `Infinity`, so it might be that either the documentation is wrong or another process/parameter is the culprate.
