### ISSUE TITLE
SingleSelect and MultiSelect throws Popper prop type console warning

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#147]
Opening a SingleSelectField or a MultiSelectField in the storybook locally (v5.0.1) throws the following warning in the console:
`Warning: Failed prop type: Popper: prop type 'reference' is invalid; it must be a function, usually from the 'prop-types' package, but received 'undefined'`.

![image](https://user-images.githubusercontent.com/12590483/84016760-07cbed80-a97e-11ea-8df1-6b153174b1c8.png)

**Comment by martinkrulltott** [comment]
relates to https://github.com/dhis2/ui/pull/141 / https://github.com/dhis2/ui/pull/141/commits/58fc4cab93853cc279f0764ec2623881db5d8232 ?

**Comment by HendrikThePendric** [comment]
yup, this was fixed in 58fc4ca, which was merged into master already, so this issue can be closed.
