### ISSUE TITLE
Can't remove MultiSelect value by clicking on the Chip while it's open

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/ui#152]
When the MultiSelect has at least one selected option and one of the `Chip`'s `x` icon is clicked while the drop down is opened. But the dropdown closes instead.
I'd expect the `x` to work (e. g. when there's a larger list and I just want to deselect a valuer after having scrolled somewhere else) and the dropdown to remain opened.

**Comment by HendrikThePendric** [comment]
I'm pretty sure this has been discussed and has been accepted as a downside of using a backdrop layer to close the option list. We were using a eventListener on the document before and apparently that was causing bugs.

**Comment by Mohammer5** [comment]
I see, I don't really remember that discussion. Maybe we can put a "copy" of the select-value-component into the popped area, so it's still possible?

**Comment by HendrikThePendric** [comment]
> I marked this as enhancement, not as bug, so it's more like something that could trigger a discussion with any outcome rather than a bug report that I'd expect to be fixed

True and it would be a good enhancement as well.

> Maybe we can put a "copy" of the select-value-component into the popped area, so it's still possible?

Yeah sth like that would probably be the best way. I think using the Popper `offset` modifier is probably the best way to get the popper and Select to overlap and flipping/shifting to still work correctly.

```javascript
const modifiers: [
    {
      name: 'offset',
      options: {
        offset: [0, inputHeight],
      },
    },
  ],
```
[See docs](https://popper.js.org/docs/v2/modifiers/offset/)

**Comment by Mohammer5** [comment]
There might be a chance that it wouldn't overlap if it doesn't fit, but then it's "just" ugly, but still better UX (cc @cooper-joe)

**Comment by HendrikThePendric** [comment]
> There might be a chance that it wouldn't overlap if it doesn't fit

aha yes, I hadn't even considered that. I suppose we could even add `display: hidden;` to the underlying input when the popper opens, so at least the user doen't end up seeing two select-inputs

**Comment by cooper-joe** [comment]
I agree this is worthwhile enhancement.

> I suppose we could even add display: hidden; to the underlying input when the popper opens, so at least the user doen't end up seeing two select-inputs

Yes, I think that a user possibly seeing duplicated non-overlapping inputs would negate any benefits to the user-experience that this enhancement brings. I would say that something like the above is a necessary part of the enhancement.

**Comment by ismay** [comment]
> I'm pretty sure this has been discussed and has been accepted as a downside of using a backdrop layer to close the option list. We were using a eventListener on the document before and apparently that was causing bugs.

Yeah, this is the pattern we've chosen to use. I think we should leave it as is. From the perspective of a very knowledgeable user, fixing this would break their expectations. Let's say they've learned that we always require a click anywhere in the UI to close any open modals and that the entire UI is disabled whilst a modal is opened (which is the pattern we went with). If we now start enabling certain inputs that goes against those expectations and they might mistakingly remove an option because they expected it to not have an effect.

**Comment by varl** [comment]
Keep as is for now, since this isn't a bug, I don't really know how to define it in JIRA.

Re-report in JIRA with an actionable description if it's still wanted.
