### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#169]
Follow up to https://github.com/dhis2/ui/pull/166. We've moved the concepts section from our user-facing docs to CONTRIBUTING.md, as it seemed more like a doc for maintainers than for users of our lib. It's still a bit rough, we should rewrite it a bit and resolve any unclear areas (like the scope of widgets, etc.).

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-52
