### ISSUE TITLE
Console warning in MenuItem

### ISSUE THREAD

**Issue by jenniferarnesen** [dhis2/ui#175]
ui@5

Here is a screenshot from Dashboards, for a disabled MenuItem

<img src="https://user-images.githubusercontent.com/6113918/84800510-ca391700-afb2-11ea-833b-fd67ea33e048.png" width="300" />

I think the problem is on this line: https://github.com/dhis2/ui/blob/master/packages/core/src/MenuItem/MenuItem.js#L69

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-45
