### ISSUE TITLE
SingleSelect doesn't allow clicking the already selected option

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#178]
https://jira.dhis2.org/browse/TECH-396

When selecting options from a `SingleSelect`, the already selected option isn't clickable and doesn't display `cursor: pointer`. I.e. to keep the already selected option, one has to click outside of the `SingleSelect` to close it. Verified with @cooper-joe that this is a bug.
Can be seen here https://ui.dhis2.nu/demo/?path=/story/singleselectfield--default, by clicking the select field and trying to select **one**, which is preselected.

**Comment by ismay** [comment]
We discussed this a bit on slack: https://dhis2.slack.com/archives/CBM8LNEQM/p1592468093121900. The current behaviour is intentional, so it's not malfunctioning, but the suggested behaviour seems like a nice improvement. We can implement the behaviour @cooper-joe suggested as a new feature.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-74
