### ISSUE TITLE
Menu has wrong data-test attribute

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#183]
See [here](https://github.com/dhis2/ui/blob/master/packages/core/src/Menu/Menu.js#L47):

<img width="367" alt="Screenshot 2020-06-22 at 11 37 37" src="https://user-images.githubusercontent.com/7355199/85272692-d0c90200-b47c-11ea-9e2c-0463d5788e34.png">

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-59
