### ISSUE TITLE
Select's inputRef not accessible for setMenuWidth method

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#186]
We just merged #185, a bugfix for the select throwing this error (which sometimes happened, can't reproduce it reliably):

![image](https://user-images.githubusercontent.com/7355199/85413361-051aec00-b56b-11ea-82f9-1cf300dd96a1.png)

But that was just a fix for the symptom. We suspected that it's due to the debounce delaying the execution of the logic in `setMenuWidth`, and that the component is unmounted in the meantime, which means that the ref is no longer accessible in the DOM.

Might be good to see what's going wrong here exactly, as we might have missed some underlying bug that needs to be fixed.

**Comment by ismay** [comment]
If this issue does not seem that relevant I'd be ok with closing it btw, since the immediate bug seems to be fixed. In that case it can serve as extra information for the associated PR. I'll leave it to the others to decide.

**Comment by varl** [comment]
Closing for now, re-report in JIRA if it turns up again.
