### ISSUE TITLE
HeaderBar does not work on 2.30

### ISSUE THREAD

**Issue by SferaDev** [dhis2/ui#192]
### Description

Header bar does not load on 2.30 or before

### Affected @dhis2/ui-widgets versions

Applies to: ui-widgets@2.1.1 (before the monorepo) and ui-widgets@5

### Details

The ``/api/systemSettings/applicationTitle`` endpoint changed on 2.31 onwards.

https://play.dhis2.org/2.30/api/systemSettings/applicationTitle
https://play.dhis2.org/2.31.9/api/systemSettings/applicationTitle

Since the HeaderBar now uses that endpoint to load the instance name, it fails because the old endpoint in 2.30 returns plain text instead of JSON.

In the application the HeaderBar looks like:

![image](https://user-images.githubusercontent.com/2181866/86236340-382c3380-bb9a-11ea-8442-ecf564b75eac.png)

The network request is like the following:

![image](https://user-images.githubusercontent.com/2181866/86236430-55610200-bb9a-11ea-8c8f-6fcd676eb71b.png)

**Comment by SferaDev** [comment]
Introduced on https://github.com/dhis2/ui-widgets/pull/399 by @amcgee

**Comment by HendrikThePendric** [comment]
I'm closing this because dhis2-core v2.30 is no longer a supported version
