### ISSUE TITLE
ui@5 alpha - Questions

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/ui#20]
I've just tried to have a proper look at the `ui@alpha` repo and I have a few questions.
I'll use this isseu to collect questions and put the answers/discussion outcome into this issues's description

## Resolved questions

**none yet**

**Comment by Mohammer5** [comment]
The whole topic started when @HendrikThePendric asked about where to put translations. This monorepo is supposed to solve the question where to put what, but I'm confused about that.

### What's the exact purpose of `core`? Offering bulding blocks that can't be used on their own?

If so, what are `CssReset` and `CssVariables` doing in their? They're not building blocks and they can be used on their own.

### Where do we put dhis2 related stuff

And where should translations go?

### How do we tell apart a translated from a non-translated component in widgets

Of course this only applied if we decide to not supply default translations to all components currently in `widgets`.

**Comment by HendrikThePendric** [comment]
Some remarks that may contain answers:
- a lot of stuff still needs to be moved from widgets to core.
- The plan is to 
    a) move to a mono-repo 
    b) make breaking changes 
    c) move things to logical places internally
- We are at point B right now

**Comment by HendrikThePendric** [comment]
> What's the exact purpose of core? Offering bulding blocks that can't be used on their own?

Yup see BaseButton, we'll be spreading props and forwarding ref too. These should just be styled HTML elements really.

> If so, what are CssReset and CssVariables doing in their? 

yeah these probably need to be moved as well

> Where do we put dhis2 related stuff

Widgets

> How do we tell apart a translated from a non-translated component in widgets

Widgets used i18n and should provide translated defaults for texts

**Comment by Mohammer5** [comment]
Discussions moved to #21
