### ISSUE TITLE
HeaderBar should use query params to only fetch the fields it needs

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui#205]
Since the HeaderBar is a component that fetches data and is included in every single app, it would be worth minimising the amount of data that is sent over the wire. We are currently fetching all the fields that are included in the `api/me` endpoint, but we probably only need a couple of fields. So we should specify a list of fields to retrieve in `params.fields` on the `me` resource.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-73
