### ISSUE TITLE
Table can't disable zebra striping

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#207]
`Table` is lacking an option to turn off the zebra striping, shown here and in the screenshot below: https://ui.dhis2.nu/demo/?path=/story/table--static-layout.
This means that all use-cases are forced to display the zebra striping, even if this is not intended.

JIRA ticket: https://jira.dhis2.org/browse/TECH-416

![image](https://user-images.githubusercontent.com/12590483/87027390-62ef3b00-c1dd-11ea-8c2c-09584dbd9d10.png)

**Comment by Mohammer5** [comment]
Could you share the design for the table you have to work on?

Afaik the [`Table` specs](https://github.com/dhis2/design-system/blob/master/organisms/table.md) are out of date / never have been finished (CC: @cooper-joe). The codepen example contains the zebra styles.

**Comment by martinkrulltott** [comment]
Here's the spec for the ticket I'm working on: https://jira.dhis2.org/browse/DHIS2-9054
I've achieved most of it easily, except the zebra striping.

**Comment by Mohammer5** [comment]
Thanks! Clearly the design doesn't have the zebra striping, should be a quite simple change to add a prop that disables the alternating color changes.

@cooper-joe could you confirm if that's the way to go?

**Comment by martinkrulltott** [comment]
Previously confirmed by @cooper-joe [here](https://dhis2.slack.com/archives/CBM8LNEQM/p1587640618241500?thread_ts=1587381573.184700&cid=CBM8LNEQM): 

> yeah we should be able to disable row-striping

**Comment by Mohammer5** [comment]
Thanks @martinkrulltott ! Will take a look, won't take too long
