### ISSUE TITLE
User avatar initials shouldn't be a <p> tag

### ISSUE THREAD

**Issue by amcgee** [dhis2/ui#22]
When a user doesn't have a profile image their initials are shown.  (i.e. `JT` for `John Traore`).  These initials are rendered in a `<p>` tag by the `ui-widgets` Headerbar, which seems semantically incorrect.  It should probably be something neutral like `<span>` or something else that reflects its role on the page, but it is not a paragraph.

This can also easily lead to CSS leakage (inward) issues with alignment if the `<p>` tag is, for instance, assigned a margin globally (a common situation).  See screenshot below, where a `margin-bottom: 10px` from a global CSS normalization causes misalignment in the Headerbar: 

![Screen Shot 2020-04-14 at 4 59 45 PM](https://user-images.githubusercontent.com/947888/79242016-0f867e80-7e74-11ea-8531-cd2713fcdeae.png)

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-49
