### ISSUE TITLE
Implementing data entry form with validations using dhis2/ui

### ISSUE THREAD

**Issue by AniketParabAtDure** [dhis2/ui#226]
hello,
I have created a program by using the dhis2 Program management module. Now I want to build the data entry form. I am building the fresh UI by using the dhis2/ui. I am able to render the normal form that is based in the program JSON that I get from DHIS2 api and module react-final-form which is present in the dhis/ui . But I am having difficulties in handling the program rules in my form. Is there any other library that may help in handling the program rules or any other way that will help me in simplifying the program rules. I have went through the program code and files that are used in capture-app which handles the program rules but I found out that the capture-app is mainly specific for the data capturing of events and also it very difficult to understand the implementation. It would be very helpful if you could guide me to move further.

Thanks,

**Comment by HendrikThePendric** [comment]
The primary purpose of this UI library is to help people building custom DHIS2 applications. I think what you are trying to do is build a custom data-entry form and is not supported by this UI library.

**Comment by varl** [comment]
Please refer to this forum for discussing App Development topics: https://community.dhis2.org/c/development/app-development/40
