### ISSUE TITLE
D2 validation (conditions) in the custom react form

### ISSUE THREAD

**Issue by VijayAtDure** [dhis2/ui#228]
Can someone please help me how run the D2 validation (conditions) in the custom react form

We have created program rules using the DHIS2 smart setup and the form using the UI/ react components of DHIS2, however now we are unable to run the validations created using the program rule and the program rule variables API.

Would you know of a tool or a library that can be used to execute those conditions on form or if there is any other way of doing this at the moment.

**Comment by JoakimSM** [comment]
Hi @VijayAtDure,

To make me understand: Are you talking about creating a custom form in the Maintenance app and opening this in the Capture app/Tracker capture app or are you creating a new DHIS2 App where you would like to run program rules?

**Comment by VijayAtDure** [comment]
@JoakimSM Following is my use case.

Use Case:

To support a standalone data entry project where forms are generated using DHIS 2.34 while the frontend is being built using the latest react UI components on tracker capture app. This includes registration and other stages for data capture.    

Components Used:
●	React js, where following libraries are imported.
○	@dhis2/ui
○	@dhis2/d2-i18n
○	@dhis2/app-service-data
○	@dhis2/app-service-config
○	@dhis2/app-runtime
○	@dhis2/ui-forms
Scenario:

The registration form with multiple stages is built using React Final Form which is bundled with @dhis/UI. 

These forms have their fields and validations as created using DHIS2 control panel. The rules are created using DHIS program rule and program rule variables and these are mapped to the specific fields. 

Following is the example/sample program rule and program rule variables to demonstrate the structure of these rules.

●	Program Rule Variable
{
"programRuleVariables": [
		{
            "id": "yLKUjYHxax6",
            "displayName": "Accomodation I",
            "programRuleVariableSourceType": "DATAELEMENT_NEWEST_EVENT_PROGRAM",
            "useCodeForOptionSet": true,
            "program": {
                "id": "nSy7PFqQykt"
            },
            "dataElement": {
                "id": "Z6CHM9ekYD6"
            }
        		}

]
}

●	Program Rule
	{
		"programRules": [
			{
	"id": "VRZPDEadfLA",
            "condition": "d2:hasValue( #{Accomodation I}) && #{Accomodation I} == '02'",
            "displayName": "Accomodation I",
            "description": "Hided Accomodation I",
            "programStage": {
                "id": "qK7p1A8UyKS"
            },
            "program": {
                "id": "nSy7PFqQykt"
            },
            "programRuleActions": [
		{
                    "id": "yd1Je6SKqmg",
                    "programRuleActionType": "HIDEFIELD",
                    "dataElement": {
                        "id": "SzxSWo2N4GB”
                    }
                }

]
}
]
}

Considering the above mentioned program rule and program rule variable; the field with data element id “Z6CHM9ekYD6” performs certain actions which on a set condition. The condition which needs to be satisfied or executed is mentioned in the program rule variable. 

Issue:
●	There is no common identifier between program rule and program rule variable apart from “displayName” 
●	The condition cannot be directly executed in React final form

We have explored the library program-rule-engine to execute the rules however the module does not have enough documentation to understand how it work. 

Following is the command/code mentioned in the library that execute rules, however it is not clear what parameters need to be passed as argument instead of args.

	d2Rule.execute(args*)

**Comment by varl** [comment]
Please raise a topic here: https://community.dhis2.org/c/development/app-development/40

I am closing this issue as we are moving away from GitHub Issues.
