### ISSUE TITLE
Headerbar should hide Interpretations and Message badges when user doesn't have access to those apps

### ISSUE THREAD

**Issue by amcgee** [dhis2/ui#23]
The COVID user at https://covid.dhis2.org/demo/dhis-web-dashboard/ doesn't have access to Interpretations or Messaging apps, but the Headerbar still shows badges which link to those apps.

Interestingly, the user *does* have access to some interpretations, just not the app itself.  I think in this case it's still the right move to hide the badge.

**Comment by HendrikThePendric** [comment]
We still have an open JIRA issue for upgrading the HeaderBar version in various apps, but from the perspective of the UI library, I think we can consider this done and close this issue, see https://github.com/dhis2/ui/pull/116
