### ISSUE TITLE
Create example implementation of uber-based layering approach

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#25]
We talked a bit about the approaches people are using in the wild for managing paint order here: https://github.com/dhis2/ui/pull/10. There's an approach that Uber's taking that seems interesting to me, but it's difficult to know exactly how it'll work out for us without actually test-driving it a bit.

This issue is a reminder so the talks about our z-index strategy doesn't get lost, and also a reminder to me to create a small example implementation, so that we can see how it'd function IRL.

**Comment by ismay** [comment]
Wasn't it the plan for me to make a sketch and see how this'd work? (As in, low priority, far future)

**Comment by ismay** [comment]
I'll reopen this, hope you don't mind. I'd be curious to see how this approach'd work exactly.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-79
