### ISSUE TITLE
Transfer: add a prop for scrolling source to top

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#253]
**Affects [DHIS2-9274](https://jira.dhis2.org/browse/DHIS2-9274)**

For Transfer, when custom filters are applied that changes the `options` param, the picked item list doesn't scroll back to the top. 
E.g. If `options` contain 40 items and the user has scrolled down to the last one and applies a filter which will change the `options` to completely different set of items, the previous scroll position is kept leaving the user scrolled far down in a new item list.

Live example: https://codesandbox.io/s/ui5-transfer-paging-0nzhz?file=/src/App.js (scroll down and enter "1" as the search filter).

In DV we have the following cases which changes the `options` param:

- Initial load - _will be at the top since no scrolling can be made prior to this_
- Scrolling to the end, this will trigger the `onEndReached` and add more options (if available) - _should not scroll to top_
- Applying/changing a server-side filter, will fetch a new set of data from the server - _should scroll to top_
- Scrolling to the end when a filter is applied - _same as "scroll to the end" above, should not scroll to top_

I suggest using a param to "reset" (scroll back to top) the position, which DV will trigger when the server-side filter is changed and the data set is replaced

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-70
