### ISSUE TITLE
FlyoutMenu inside a Popover: a double border is shown 

### ISSUE THREAD

**Issue by edoardo** [dhis2/ui#254]
`Popover` and `FlyoutMenu` components seem to render the same type of border.
When `FlyoutMenu` is used within a `Popover` component, 2 borders are shown as seen in the screenshot below.
The typical use case is a menu opened below a button, like the Download menu in DV and the More... menu in dashboards app.

Screenshot
![Screenshot from 2020-08-25 10-51-53](https://user-images.githubusercontent.com/150978/91720930-31b93880-eb98-11ea-84ec-dfc702162796.png)

Is there any way to avoid this?

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-69
