### ISSUE TITLE
FlyoutMenu with a disabled MenuItem requires onClick

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#255]
Using a `FlyoutMenu` with a `MenuItem` that’s `disabled` without an `onClick` prop throws the following error (screenshot). 

In the [stories](https://ui.dhis2.nu/demo/?path=/story/flyoutmenu--default) `MenuItem`s are used without `onClick` successfully, but if the `disabled` prop is added it throws the console warning.

![image](https://user-images.githubusercontent.com/12590483/91723470-17815980-eb9c-11ea-8d1c-6552a34d8383.png)

[Simple example](https://codesandbox.io/s/ui-flyout-menu-disabled-warning-786cf?file=/src/App.js)

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-68
