### ISSUE TITLE
Transfer: onEndReached not triggered if an item is selected

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#257]
The `onEndReached` usually triggers when scrolling all the way down in the left side of the `Transfer` component. However if the user selects any item from the left side (i.e. clicks it once), the `onEndReached` doesn't trigger any more.

As seen in [this example](https://codesandbox.io/s/ui5-transfer-onendreached-when-selected-19rui?file=/src/App.js).

**Comment by amcgee** [comment]
’m pretty sure this is sourced here - remountCounter is not a dependency of the useEffect, so it is always 0 (the initial value).  This line should use the functional version of the set function to increment.  https://github.com/dhis2/ui/blob/7346eb8905ffb74f7121f50aca01b4ebc85aa8fa/packages/widgets/src/Transfer/OptionsContainer.js#L35

There’s a chance this is unrelated, but it smells like it could be relevant to me

**Comment by amcgee** [comment]
I’m also skeptical about using a state variable for `resizeObserver`, seems superfluous to me

**Comment by amcgee** [comment]
Note that I believe this happens any time the props of the Transfer OptionsContainer change, not just when something is selected (i.e. unselecting doesn't fix it)
