### ISSUE TITLE
Infinite scrolling improvements

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui#276]
I'm writing this issue after reviewing #272. The following is the case:
- The `IntersectionDetector` component is a public component so making changes to it would trigger breaking change. We don't want that.
- We have learned in the `Transfer` that the `IntersectionObserver` doesn't pick up on intersection changes due to elements that changing size (i.e. adding extra options to the option list). So that was a problem that needed to be fixed.
- Currently we have a working solution in the `Transfer` which works by keeping track of a resize count and updating a `key` prop on the `IntersectionDetector` to force a remount. This is OK for now, but it's be nice to address this in a better way...

I have some ideas for this:
- If we extract most of the logic we have in the `IntersectionDetector` into a custom hook, i.e. `useIntersectionDetection`. The difference between the current logic and this custom hook would be that you could specify additional dependencies which would be added to the dependency array in the call to `useEffect`. This would offer more control in over when the effect re-runs, and would be a better option than triggering a remount.
- Use this hook in the `IntersectionDetector`, this will become a very small component in terms of LoC.
- Introduce another component with a slightly more specific purpose/name i.e. `ScrollBox` / `InfiniteScroller` 🤷‍♂️  that also uses the new hook, and this time add an additional dependency for the height of the container. So this way whenever the container changes height the effect would run.

Below is a fully untested hypothetical implementation of the custom hook:
```javascript
export const useIntersectionDetection = ({
    rootEl,
    intersectionEl,
    threshold,
    onChange,
    additionalDependencies,
}) => {
    const isIntersecting = useRef()

    useEffect(() => {
        if (rootEl && intersectionEl) {
            const onIntersection = entries => {
                // Currently there's no way to supply multiple thresholds,
                // so a single entry can be assumed safely
                const [entry] = entries

                // Make sure the callback is not called multiple times
                // if there is no change
                const intersectionChange =
                    entry.isIntersecting !== isIntersecting.current

                if (intersectionChange) {
                    isIntersecting.current = entry.isIntersecting
                    onChange({
                        isIntersecting: entry.isIntersecting,
                    })
                }
            }

            const observerOptions = { root: rootEl, threshold }
            const intersectionObserver = new IntersectionObserver(
                onIntersection,
                observerOptions
            )

            intersectionObserver.observe(intersectionEl)

            // Make sure to clean up everything when un-mounting.
            // Using an arrow function instead of just returning
            // the disconnect function for better readability.
            return () => intersectionObserver.disconnect()
        }
    }, [rootEl, intersectionEl, ...additionalDependencies])
}
```

I'm not at all sure if this implementation works, we need to examine if the the effect runs when we expect it to. I'm particularly worried that this effect might run too often because of the way we are creating the dependency array.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-66
