### ISSUE TITLE
Disabled toggle styles only affects text labels

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui#294]
Radio, checkbox and switches use a `label`. When the toggle is disabled the label uses a `.disabled` style that applies `color: ${theme.disabled};`. However, this only works if the label is text.

[Non-text labels for these toggles are valid](https://ui.dhis2.nu/demo/?path=/story/radio--image-label), and need to also display a disabled state.

I was going to make a PR to fix this using an `opacity` instead, but I wonder if there is a better solution? Ideally the `theme.disabled` style would still be used for text labels and something else for other types. Perhaps it is enough that an app handles this by writing their own css rules for disabled non-text labels, and therefore this is an non-issue?

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-64
