### ISSUE TITLE
Simplify button styles

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#298]
The button styles need to be simplified (in my opinion). The amount of styles is too large to reasonably allow a dev to comprehend what will happen when changing styles. It wouldn't surprise if that'll cause bugs if we leave this as is.

Plus, there are [duplicate selectors](https://stylelint.io/user-guide/rules/no-duplicate-selectors), and there's [descending selector specificity](https://stylelint.io/user-guide/rules/no-descending-specificity) (stylesheets are most legible when overriding selectors always come after the selectors they override).

Also, the interactions between the button settings and the icon container seem like they might be easier to comprehend if the icon container were a react component, instead of managing the interactions through composing css classes.

p.s.: I don't mean we should change the styles themselves (as in the way the buttons look), I mean we should make the code more maintainable.

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-63
