### ISSUE TITLE
className prop targets child element instead of top level parent

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#39]
Various components handle `className` differently. Ideally there should be a way to target the top level parent element of the rendered output of the component.

----

Case examples:

`SingleSelect` and `MultiSelect`
![image](https://user-images.githubusercontent.com/12590483/80081999-fe183300-8553-11ea-9d8f-eba944a8ae8a.png)

`SplitButton`
![image](https://user-images.githubusercontent.com/12590483/80082032-0bcdb880-8554-11ea-8453-a83df2c4d317.png)

`ToggleGroup` / `RadioGroup` - applies to the children, leaving an unstylable `div` at the top level.

**Comment by martinkrulltott** [comment]
The `SingleSelect` and `MultiSelect` blocks a style change for https://github.com/dhis2/data-visualizer-app/pull/850 (YearOverYearSelect component)

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-47
