### ISSUE TITLE
Scope for ui@5

### ISSUE THREAD

**Issue by varl** [dhis2/ui#41]
# 5.0.0 scope

- Co-locate UI libraries in repo `dhis2/ui`
- Introduce the `@dhis2/ui` top-level package and main entry-point for the UI libraries.
- Keep `@dhis2/ui-core` and `@dhis2/ui-widgets` as-is:
- - **core**: Ready-to-go building blocks for UI
- - **widgets**: Components that need translations and/or DHIS2 API
- Internal split to:
- - `@dhis2/constants`
- - `@dhis2/icons`

# Upgrade path from 4.x to 5.x

- Generally all imports from either `@dhis2/ui-core`, `@dhis2/ui-widgets`, and `@dhis2/ui-forms` can be replaced by a single namespace: `@dhis2/ui`.
- There are some cases where we have rename a component to avoid name conflicts.
- Some components have been dropped, see the CHANGELOG for more information.

**Comment by varl** [comment]
# *Field components

One thing I've been thinking a lot about are our *Field components. In some cases they provide some value, but in the case of **RadioField**, **SwitchField**, and **CheckboxField** they are just wrappers for the **ToggleGroupField** component that takes a **Checkbox**, **Radio**, or **Switch** components.

I've argued in the past that all form controls should have a *Field counterpart for consistency reasons, but these form controls are rarely used as singular form controls as they make little sense outside of a group to choose between.

ui@5 drops **SwitchField**, **RadioField**, already. So, let's drop **CheckboxField** as well.

**Comment by HendrikThePendric** [comment]
Don't forget the breaking changes I've been working on:
Done:
- https://github.com/dhis2/ui/pull/10
- https://github.com/dhis2/ui/pull/12

In progress:
- https://github.com/dhis2/ui/pull/44

It's important this last one makes it in too so we don't end up introducing V6 soon 😉

**Comment by varl** [comment]
Now that the Transfer is in ui@alpha, we should do #50 before releasing as it will change the option style to string-based.
