### ISSUE TITLE
ComponentCover doesn't cover parent component

### ISSUE THREAD

**Issue by amcgee** [dhis2/ui#43]
The `<ComponentCover />` component has css with `width: inherit` and `height: inherit`.  This works well if the **parent** of the cover has explicit `width` and `height` set, bit it breaks when the parent is dynamically sized - for instance, if the parent is the child of a `flex` container.

Is there reason `inherit` was chosen and could we perhaps support another mechanism to cover dynamically-sized parent elements?  In many cases `width: 100%`, `height: 100%` may work, but that could have problems determining the proper height.

**Comment by amcgee** [comment]
@HendrikThePendric is this fixed in v5 then?

**Comment by HendrikThePendric** [comment]
Yeah it has. 
https://github.com/dhis2/ui/blob/744abcb2c0ebc0f50dae0cfb7417f1510d070a6e/packages/core/src/ComponentCover/ComponentCover.js#L36-L44

Only gotcha is that the parent needs a non-static position, which would be something for the docs.
