### ISSUE TITLE
Uniform organisation for our feature files / step definitions in cypress/integration

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#45]
We currently have e2e stories defined in core, widgets and forms. In `cypress/integration` we have a `forms` folder that contains the feature files and step definitions for the `forms` stories. But for `core` and `widgets` those are all mixed at the root of `cypress/integration`.

Once everything has settled after the move it'd be nice to have uniform organisation in this folder. I'd propose to organise all our step/feature files the way the forms ones are organised, so:

```
cypress/integration
  - forms
  - core
  - widgets
```

**Comment by Mohammer5** [comment]
I'd prefer if we put the feature files in the same folder as the actual components (we could put them in a `spec` sub folder). and then tell cypress that the `packages` folder is the actual `integration` folder. 

We're already putting everything together into one component folder (component, stories, jest tests), so it'd only make sense to put the features there as well

**Comment by Mohammer5** [comment]
Just confirmed, with the following addition to the `cypress.json` it works:

```
    "integrationFolder": "packages",
```
