### ISSUE TITLE
Clarify the assumptions made in our features/step definitions/stories

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#48]
Follow up from: https://github.com/dhis2/ui/pull/46#discussion_r417196738

In our stories we sometimes use the title `Default`, or similar titles, which aren't very descriptive. It's easy for such a story title to get out of sync with what it's actually meant to contain, especially if it's reused in multiple test scenarios. A similar thing goes for our step definitions.

I'm in favour of stating exactly what goes on in a story, or step (and in the case of a step, asserting the statements made in that step), to prevent title and content drifting apart.

So if a story prepares a test environment with multiple properties (for example: red, and highlighted, and active, etc.), I'm in favour of listing all of that in a Single Given if it's all prepared in a single step definition (loading the story). I'm only in favor of breaking it out into Given's and And's if removing that step from the feature will also remove the property from the test environment (so for example if removing `And is selected` will also mean that it'll no longer be selected in the test).

Otherwise it's hard to reason about the feature files, step definitions or stories in isolation, and you can only work on them when you understand how they interact. I'd prefer devs to only have to think about the current file they're working on, seems easier to not make any mistakes that way.

**Comment by ismay** [comment]
See also: https://mtlynch.io/good-developers-bad-tests/

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-58
