### ISSUE TITLE
Components should be able to accept a ref

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui#57]
All of our components that have a clear "root-element" should be wrapped in `React.forwardRef`, and apply a ref to that root element. This would be a good thing in general, for various use-cases in apps, but specifically for allowing our components to be used as anchor-elements for popper-based components.

**Comment by HendrikThePendric** [comment]
As an additional note:
- I have previously discussed this with Viktor 
- At that time the plan was to add refs to the `*Base` components, which would be extracted from ui-widgets into ui-core.
- However, it now looks like making this split is still up for debate, and will be delayed at the very least
- But the use-cases are quite relevant, I think, so I think we should just move ahead with this

**Comment by varl** [comment]
I think it's safe to say that we are going to use the `Base` component concept.
