### ISSUE TITLE
Spreading props

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui#58]
Since it's hard to predict how exactly our low-level components are going to be used, it could be beneficial to spread props onto them. Some relevant use-cases that are currently not supported, but that would be if we started spreading props:
- adding keyboard event listeners
- adding mouse event listeners
- adding aria attributes
- adding data attributes

Before implementing this we should first establish:
1. How other UI libraries deal with these type of things, perhaps spreading props isn't the only option to support the use-cases above
2. Whether the additional benefits outweigh the additional level of unpredictability

**Comment by varl** [comment]
This ties into the `Base` components, as they would spread all props added to them.
