### ISSUE TITLE
Transfer component - infinite scrolling

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#62]
When handling a large amount of items in the Transfer component there's a need to support infinite scrolling, to be able to initially load a subset of data and sequentially load more when scrolling. Details: https://jira.dhis2.org/browse/TECH-378

**Comment by ismay** [comment]
We (tapps subset) talked about this a couple of days ago. The Select has a similar requirement. We were thinking of adding a prop `onEndReached` (or something of that nature). `onEndReached` accepts a callback, that will be called when the user has scrolled to the end of the list.

That way the app can handle whatever needs to happen when the end has been reached (like loading more items, supplying more options, etc.), and the component doesn't have to know anything about the fetching logic, etc.

**Comment by Mohammer5** [comment]
I think our idea was to create a component that will offer these event as an api and then re-use it in both the Transfer & *Select components (and wherever needed)

**Comment by Mohammer5** [comment]
Implemented
