### ISSUE TITLE
Transfer component - loading spinner

### ISSUE THREAD

**Issue by martinkrulltott** [dhis2/ui#63]
When searching using a filter in the Transfer component there's a need to display a loading spinner while the result is getting fetched.  Details: https://jira.dhis2.org/browse/TECH-379

**Comment by ismay** [comment]
Not sure about the architecture, but maybe this could be implemented in a similar way as the Select's `loading` indicator.

**Comment by Mohammer5** [comment]
Yeah, that should be no problem! Wondering if we'd need that for both the `source`- as well as `picked` options' sides?

**Comment by ismay** [comment]
> Wondering if we'd need that for both the source- as well as picked options' sides?

Yeah I was wondering that as well. I assume only the source side? @cooper-joe, what do you think?

**Comment by cooper-joe** [comment]
Yeah, let's include for both sides. There could definitely be cases where a slow connection is waiting to get the 'picked' options from the server. I'll make sure it's on the spec!

**Comment by ismay** [comment]
So would the loading scenarios be independent? Or would a single loading flag suffice? I guess as soon as you don't have the options, you can't display the selected options either, right?

**Comment by cooper-joe** [comment]
> So would the loading scenarios be independent? Or would a single loading flag suffice? I guess as soon as you don't have the options, you can't display the selected options either, right?

Good question. I think in the vast majority of cases it will be fine to control the loading with single flag. There could be some cases where `picked` options are loaded from a separate place than `source` options, but you'd probably want to put the entire component into `loading...` mode then anyway. So, I think a single loading flag would suffice.

**Comment by martinkrulltott** [comment]
> Yeah, let's include for both sides. There could definitely be cases where a slow connection is waiting to get the 'picked' options from the server. I'll make sure it's on the spec!

I agree to include it for both sides. For https://jira.dhis2.org/browse/DHIS2-8831 the available options are fetched async from the server, while the picked are available from the start. However, since the picked options get generated by matching those with the available ones, this means that the right side will display "No items selected" while the available options are loaded.

In the case above, the loading is fine to control with a single flag, but I suppose there could be cases where both sides are fetched async independently. However it doesn't make sense to display one side before the other, since that could flash options that are/aren't available incorrectly before both sides are loaded.

E.g. X, Y, Z are available. Z is selected. Both are fetched async independently. 
- If the available return first, it will display X, Y, Z as available (incorrect, only X, Y are actually available) until the selected are returned as well.
- If the selected are returned first, it won't be able to match Z with an available option, leading to "No items selected" until the available are returned as well.

This would however be different (but still applicable) if the future flag "distinctSourceAndPickedOptions" (as discussed with @Mohammer5) is in place, which separates the source and picked options, to display selected options that aren't available in the source.

**Comment by Mohammer5** [comment]
Loading states are now present. For the selected options during the loading state, this has been addressed in #143
