### ISSUE TITLE
Popper dropdown for select positioned incorrectly after resize

### ISSUE THREAD

**Issue by ismay** [dhis2/ui#67]
I was only able to reproduce this on FF (on macos). After resizing the browser window to the left, with the select dropdown open, sometimes the dropdown is sometimes positioned too far too the left (16px):

<img width="543" alt="Screenshot 2020-05-12 at 17 22 14" src="https://user-images.githubusercontent.com/7355199/81712799-5799c080-9475-11ea-9ecf-d8a1ebdaa9c2.png">

Hendrik and I looked at this for a moment, but weren't able to find out what exactly's causing this. We were thinking that it might be the event listeners and resize observer competing (or the rerenders due to the changed menuwidth interfering). There seems to be some sort of race condition somewhere, because it doesn't occur every time.

**Comment by ismay** [comment]
One thing that I did notice is that setting placement to `bottom-start` _does_ resolve the placement inaccuray when resizing to the right, so it's just resizing to the left that doesn't work after that.

**Comment by ismay** [comment]
I've moved it to 5.1.0. I wouldn't be surprised if this has been resolved by the changes we've made in the meantime, and it's not critical to ship this with v5.0.0 in my opinion.

**Comment by varl** [comment]
Re-report in JIRA if it is something that we want to fix. 16px sounds suspiciously like the window is going from _without_ a scrollbar to _with_ a scrollbar as you are making the window narrower.
