### ISSUE TITLE
Switch to react-popper for our Popper

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/ui#68]
The popper.js developers have introduced [`react-popper` v2](https://popper.js.org/react-popper/v2/), and unlike v1, this looks really great. It would make a lot of sense to start using that for our `Popper`.

**Comment by ismay** [comment]
@HendrikThePendric Which milestone would you put this in?

**Comment by HendrikThePendric** [comment]
This has been merged into alpha already
