### ISSUE TITLE
 Missing components in ui-core vs. d2-ui-core

### ISSUE THREAD

**Issue by varl** [dhis2/ui#75]
# `ui-core`

* [x] [Snackbar](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/feedback-snackbar) (implemented as AlertBar)

# `ui-widgets`

* [ ] [Sidebar](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/sidebar)
* [x] [TreeView](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/tree-view)
* [x] [Tabs](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/tabs)
* [ ] [PeriodPicker](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/period-picker)*
* [ ] [DatePicker](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/form-fields/DatePicker.component.js)*

_* These are blocked by the multi-calendar date-engine that is going to power these components. This engine will be built by @abyot_

# Unsure

* [ ] [Pagination](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/pagination)

* [ ] [Layout Components](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/layout)
  * Not needed in `ui-core`

* [ ] [ListSelect Components](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/list-select)
  * Not needed in `ui-core`
  * The searchable list component could be of interest

* [ ] [Message](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/messages)
  * Could be used as the message for form input components as well

* [ ] [MultiToggle](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/form-fields/MultiToggle.js)

* [ ] [SvgIcon](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/svg-icon)
  * Wrapper for MUI Icons, which we don't want to use anymore
  * Should not be part of `ui-core`, could have its own lib (ui-icons?)

# No.

* [x] ~[Heading](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/headings)~
    Will be handled as part of the Typography implementation.

* [x] ~[ControlBar](https://github.com/dhis2/d2-ui/tree/master/packages/core/src/control-bar)~
    The control bar component was created specifically for the dashboard and has been removed from d2-ui: https://github.com/dhis2/d2-ui/pull/431 so we do not need to port it.

**Comment by HendrikThePendric** [comment]
I think the information in this issue has become outdated so I am closing this issue.
