### ISSUE TITLE
Left aligned labels for composed 'Field' elements

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui#78]
Continuing the discussion from https://github.com/dhis2/ui-core/issues/457

> Is this in addition to the "Inline label" that's specced in: https://github.com/dhis2/design-system/blob/master/molecules/select.md#inline-label?
> 
> And, could the "inline label" extend to the `InputField` in the future?

Good point @varl. I actually don't think we need both 'left positioned label' *and* 'inline label', the use cases overlap too much. I included the 'inline label' option for `select` because I wanted to offer an out-of-the-box 'compact' solution for table headers and such spaces, where it's quite important a default `select` isn't used. A left positioned label would solve for that too.

Therefore, if we offer `position:left` for labels I think we can remove the 'inline-label' option on the `select`. I assume this would simplify the build of the `select` field too, and we avoid the awkward question you raised: why isn't 'inline label' available for `input` too?

**Comment by varl** [comment]
Please re-report in JIRA with an actionable issue.
