### ISSUE TITLE
Menu: update/extend from specs

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui#80]
I've updated the `menu` component with some extended functionality and cleaned up visuals. 
[The updated documentation](https://github.com/dhis2/design-system/blob/master/molecules/menu.md)
[Direct link to updated design specs](https://sketch.cloud/s/DwkDk/a/EpllLR)

The required changes, summarised:

- [x] set up min/max width/height, detailed in spec notes
- [x] adjust font size and padding for dense
- [x] dense divider
- [x] section headers (regular/dense)
- [x] destructive type menu item
- [x] disabled state menu item
- [x] icon size standardization (regular/dense)

The design spec is much more detailed now, (the last one came straight out of MUI), the menu will now be more polished and extendable with the new features here 👍

**Comment by HendrikThePendric** [comment]
Fixed in https://github.com/dhis2/ui/pull/44
