### ISSUE TITLE
Can't pre-push because husky throws error

### ISSUE THREAD

**Issue by paschalidi** [dhis2/ui#93]
Hey! 👋 

Getting an error from `husky` when trying to push. Any ideas? Did anyone had the same before?
<details>
<summary>Click here to see terminal debug info</summary>
<pre>
husky > pre-push (node v13.11.0)
$ d2-app-scripts test
Running tests... 
FAIL src/__tests__/StackedTable.test.js
  ● Test suite failed to run

    Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/user/dev/dhis2/ui-core/node_modules/@babel/helper-compilation-targets/package.json

      at Object.<anonymous> (node_modules/@babel/preset-env/lib/debug.js:8:33)
      at Object.<anonymous> (node_modules/@babel/preset-env/lib/index.js:11:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.996s
Ran all test suites.
[ERROR] Tests failed 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky > pre-push hook failed (add --no-verify to bypass)
Hook process exited.
</pre>
</details>

**Comment by ismay** [comment]
Not sure if this is still an issue, but does running `yarn run build` before the push resolve it maybe?

**Comment by HendrikThePendric** [comment]
@paschalidi is still still an issue for you or can this be closed?
