### ISSUE TITLE
Add active state for Button

### ISSUE THREAD

**Issue by jenniferarnesen** [dhis2/ui#95]
In dashboards, each dashboard item has a button that toggles the open/closed state of the item interpretations and description. I am trying to use the ui-core Secondary button for this, but it doesn't seem to currently support the 'active' state (which would indicate that the interpretations section is currently visible). Would it be possible to support this very soon (like this week?) 🙏 

Tagging @cooper-joe in case he wants to comment on this.

Below is a mock up of what it would look like when active:

![image](https://user-images.githubusercontent.com/6113918/75119834-67a2c080-563b-11ea-84df-647359b76c71.png)

The button also gets a blue border due to the `:focus` state. I'm pretty sure this is not wanted for these buttons. If these requests are out of scope for the ui-core button, let me know soon and I'll create my own button for this.

**Comment by HendrikThePendric** [comment]
@cooper-joe can this issue be closed?

**Comment by cooper-joe** [comment]
@HendrikThePendric Yeah, I'm tracking this in my design to-do board and will report it when it's ready with a spec.
