### ISSUE TITLE
Misaligned arrow icon in nodes

### ISSUE THREAD

**Issue by cooper-joe** [dhis2/ui#96]
https://github.com/dhis2/ui-core/pull/743 adjusted the arrow icon for dropdown/split buttons. The icon is also being used in the `Node` component. The icon is now misaligned in the `Node`.

![image](https://user-images.githubusercontent.com/33054985/73438519-75239e00-434e-11ea-9be4-f4b7d3c8b68b.png)

**Comment by Mohammer5** [comment]
again.. :roll_eyes:

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-75
