### ISSUE TITLE
Document required props on children for parent components that rely on them

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/ui#99]
@HendrikThePendric, @ismay and I were talking about how we can check if some components follow a certain api so they'd work when used with another component. We've encountered some tricky scenarios which are hard to impossible to test (like testing if a component implemented a specific prop that we'll provide automatically; checking prop-types is not an option).

So the best way to cover this is by having proper docs which contain "How to create custom [Component name]" sections, which a developer most likely will read anyways when creating custom components.

Here's a list of components that require these docs:

- [ ] SingleSelect
  Options need to have a `value` and `label`, and accept an `onClick` prop
- [ ] MultiSelect
  Options need to have a `value` and `label`, and accept an `onClick` prop
- [ ] CheckboxGroup
  Checkboxes need either have or accept some specific props
- [ ] CheckboxGroupField
  Checkboxes need either have or accept some specific props
- [ ] RadioGroup
  Radios need either have or accept some specific props 
- [ ] RadioGroupField
  Radios need either have or accept some specific props
- [ ] SwitchGroup
  Switches need either have or accept some specific props 
- [ ] SwitchGroupField
  Switches need either have or accept some specific props

**Comment by varl** [comment]
https://jira.dhis2.org/browse/LIBS-56
